version: "3"

services:
    php:
        build:
            context: ../
            dockerfile: build/configs/php/Dockerfile
        volumes:
            - ../:/app
        networks:
            - default
            - traefik

    web:
        image: nginx:latest
        labels:
            - traefik.enable=true
            - traefik.http.routers.bbb.entrypoints=http,https
            - traefik.http.routers.bbb.rule=Host(`{{ appName }}.intren.test`)
            - traefik.http.routers.bbb.tls=true
            - traefik.http.routers.bbb.service=bbb
            - traefik.http.services.bbb.loadbalancer.server.port=80
        volumes:
            - ../:/app
            - ./configs/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - traefik
            - default

    node:
        image: node:lts
        volumes:
            - ../:/app
        networks:
            - default

networks:
    default:
        external: false
    traefik:
        external:
            name: traefik-gateway
