version: "3"

services:
    php:
        build:
            context: ../
            dockerfile: build/configs/php/Dockerfile
        volumes:
            - ../:/app
            - symfony_framework_cache:/app/{{ appName }}/var/cache
        networks:
            - default
            - traefik

    web:
        image: nginx:latest
        labels:
            - traefik.enable=true
            - traefik.http.routers.{{ appName }}.entrypoints=http,https
            - traefik.http.routers.{{ appName }}.rule=Host(`{{ appName }}.intren.test`)
            - traefik.http.routers.{{ appName }}.tls=true
            - traefik.http.routers.{{ appName }}.service={{ appName }}
            - traefik.http.services.{{ appName }}.loadbalancer.server.port=80
        volumes:
            - ../:/app
            - ./configs/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - traefik
            - default

    node:
        image: node:lts
        volumes:
            - ../:/app
        networks:
            - default

networks:
    default:
        external: false
    traefik:
        external:
            name: traefik-gateway

volumes:
    symfony_framework_cache:
